server:
  port: 80
  address: 0.0.0.0

spring:
  main:
    banner-mode: off
  datasource:
    url: jdbc:mysql://localhost:3306/AiPainting
    username: root
    password: yuan123456
    driver-class-name: com.mysql.cj.jdbc.Driver


  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

mybatis:
  mapper-locations: classpath:mapper/*.xml

#  configuration:
#    # Other configurations...
#    plugins:
#      - com.github.pagehelper.PageInterceptor
#logging:
#  level:
#    org.mybatis: DEBUG


#  documentation:
#    swagger-ui:
#      enabled: true
#  swagger:
#    title: AiPainting
#    description: AiPainting desc
#    version: 1.0
#    contact:
#      name: wangxinyuan
#      email: wxy@email.com

